### ISSUE TITLE
No preview

### ISSUE THREAD

**Issue by grahamperrin** [Bill13579/tabby#1]
No preview when I point at (hover over) listings for pages such as: 

- https://medium.com/firefox-test-pilot/min-vid-graduation-report-9ad74dc37c1

## Environment

Waterfox 56.1.0_10 on FreeBSD-CURRENT.

**Comment by Bill13579** [comment]
Tabby can only show preview images on Firefox 59 or above, and Waterfox have not released version 59 yet, so it will not work on Waterfox 56.

# Technical Details
Because Tabby get preview images by using the Tabs Api's `captureTab()` method, it can only work on Firefox 59 and above. It seems that Waterfox have not yet implemented the captureTab method.
