### ISSUE TITLE
Request for option to disable "what's new" tab opening upon extension update

### ISSUE THREAD

**Issue by norweeg** [Bill13579/tabby#143]
Could you include an option to disable the rather intrusive pop-open tab highlighting what's new when Tabby updates?  I use Firefox synchronized across many different systems and get this tab on **each** when I open Firefox for the first time after a Tabby update.  I don't really care to see it even on one of them, but I especially don't need to be told "what's new" on every system I use Firefox on just because Tabby has had a new release.  I would love an option to opt-out of learning about "what's new"

**Comment by Bill13579** [comment]
3.1 should fix it.

**Comment by norweeg** [comment]
> 3.1 should fix it.

@Bill13579  so where can I find this option?  I returned to check the status of this issue when the extension updated today, grabbing focus from my active tab to, once again, show me an update changelog that I don't really care about and would rather not see??

**Comment by Bill13579** [comment]
Ah my bad, there was a bug where the what's new page opened every time the browser updated, not just Tabby, so most bug reports related to the what's new page was about that one and reading your issue I thought you meant that as well, that was what I fixed in the last version. But I guess you meant turning it off entirely? I don't get to really put out new versions very often as a college student, and with this being a passion project and all I hoped that the occasional message from me wouldn't be too bad haha. Sure, I've added an additional option in 3.2.1 in the settings page, you'll find a label that says "Showing on major updates" beside the link to the what's new page, that's the new default; if you want to turn off all update pages, you can click on it to set it to never show instead.
