### ISSUE TITLE
Cannot install on MS Edge or Chrome

### ISSUE THREAD

**Issue by tp01-gogogo** [Bill13579/tabby#191]
I followed the steps:
Start Chrome
Go to chrome://extensions
Press on the Load unpacked button
Select the dist directory
but it shows 'ErrorManifest file is missing or unreadable'
![image](https://github.com/Bill13579/tabby/assets/111100869/2099a416-5f2d-4782-801b-7755f0a401da)

**Comment by Bill13579** [comment]
Since Chromium browsers work so differently for addons compared to Firefox I had fallen behind on Chrome compatibility with all the changes introduced in 3.0 and 3.1. It should be all caught up now on master! Some things might work differently than Firefox though and you still might encounter small problems, I'm not planning on officially releasing on Chromium again for some time.
