### ISSUE TITLE
Configure the path used by "save websites for later"

### ISSUE THREAD

**Issue by AndreC10002** [Bill13579/tabby#24]
I have no idea where Tabby saves the list of windows/tabs.  I'd like to be able to configure the location where this information is saved, so I can easily back it up.  Saving it to a mapped drive, for example, would provide automatic back ups.

Meanwhile, could you tell me where Tabby saves this information?

Thank you.

**Comment by Bill13579** [comment]
Hi! Thanks for the input. For Tabby's save for later feature, the data is currently saved in [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync), which means that I have no control of where this data is actually stored on the system, and I think is browser dependent as well. Due to this, `Export` & `Import` is definitely on my roadmap.
