### ISSUE TITLE
Popup visibile only one time out of two

### ISSUE THREAD

**Issue by psychowood** [Bill13579/tabby#45]
Tabby v2.1 on Firefox 77.0.1 (64-bit) on macOS

After updating to v2.1 I'm having a strange issue: every time I click (or invoke with the shortcut) Tabby the popup is not visible, and I have to reopen it a second time. The third time is not visible again, the fourth it is, and so on.

The issue does not appear on newly created windows, but does not seems to be directly related to the number of open tabs.

![Screen Recording 2020-06-29 at 18 11 39(1)](https://user-images.githubusercontent.com/115389/86030228-7e678280-ba34-11ea-9777-482070ee5ebe.gif)

Let me know if I can help you debug it in any way.

Thanks and keep up the good work!

**Comment by Bill13579** [comment]
Hmm... I encountered this issue a few times while developing, but I thought that was just a quirk with debugging the addon and wouldn't make it into production, since it didn't happen a lot. This is most definitely a bug. Thanks for reporting this @psychowood! Now we need to figure out what triggers this behavior. The build instructions are in the readme, so feel free to beat me to the solution! I will try to figure it out as well.

**Comment by Bill13579** [comment]
Dang. Whatever I do I can't reproduce this

**Comment by psychowood** [comment]
It stopped happening here too... but I noticed it is doing the same on another, unrelated, add-on, I'd say it is firefox related.

**Comment by Bill13579** [comment]
I agree. It's not happening on Firefox 79, so I'm guessing that whatever the issue was, it was fixed.
