### ISSUE TITLE
Save-for-Later doesn't work for large sessions

### ISSUE THREAD

**Issue by Bill13579** [Bill13579/tabby#55]
Save-for-Later currently utilizes `storage.sync`, which is great for syncing but this also creates the problem of Save-for-Later not being able to save large sessions due to the storage cap.

**Comment by Bill13579** [comment]
### Solution 1
Use local storage instead of sync storage.
#### Pros
- No more storage caps.
#### Cons
- No more syncing

**Comment by Bill13579** [comment]
### Solution 2
Use bookmarks.
- **Pros**  
No more storage caps.  
Automatic first-class syncing by browsers.
- **Cons**  
Will mess up bookmark search.

**Comment by GabrielGab** [comment]
> 
> 
> Save-for-Later currently utilizes `storage.sync`, which is great for syncing but this also creates the problem of Save-for-Later not being able to save large sessions due to the storage cap.

I have to say that  Save-for-Later , doesn't work , even in small sessions , with just 2 o 3 windows open with not more than 10 tabs each . Do you think that the scenario I present is a large session ?

**Comment by KyleRConway** [comment]
This may be a separate "feature request" as I haven't been sure how the "save for later" feature is supposed to work, but it would be great if "save for later" could save multiple sessions (possibly close/open entire, for Solution 2, bookmark folders or something). 

At any rate, exciting and useful tool.

**Comment by metasean** [comment]
Spit-balling:

Maybe take inspiration from other extensions that already do this.  Or possible share an api so that other extensions can manage this functionality in conjunction with Tabby.  (e.g. a window save/stash could be initiated directly from Tabby; if I've named a window in Tabby then that window name would be preserved during a save/stash; a new button in Tabby could open the other extension's interface for opening a previously save/stashed window)

Examples extensions:
- https://addons.mozilla.org/en-US/firefox/addon/tab-stash/
- https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/

But there are certainly a lot of other extensions in this space - https://addons.mozilla.org/en-US/firefox/search/?q=save%20tab%20groups

**Comment by Bill13579** [comment]
Implemented compression and save data optimizations in the update, this shouldn't be an issue anymore

**Comment by Bill13579** [comment]
@KyleRConway @metasean Multi-session saving should be easier to implement now that the internal apis are designed to handle it. It's on the roadmap for sure :)
