### ISSUE TITLE
Where are the sessions being saved to?

### ISSUE THREAD

**Issue by SteveH66** [Bill13579/tabby#93]
I have done a search of the issues, after reading the Wiki, and looking at newest features in version such-and-such, etc.  I have been unable to find where tabby is saving the sessions to when you save them for later.  I would think this would be a **very** important piece of information for people, so we could know where to go look for sessions if there were some kind of problem.  Like say your hard-drive crashed?  Browser profile got wiped out?  Thanks for any information you can give me on this issue.

**Comment by Bill13579** [comment]
Tabby saves all its sessions right here: [browser.storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) (and [browser.storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) in the future)

Among a few options for an extension to store data it seemed to be the most reliable one, but I'm not sure even it would survive a profile wipe or hard drive crash! I think that `localStorage` is implemented in FF through Sqlite so if you could track the file down you could recover it. Although, since its sync storage, if you had a FF account setup it would be synced!
It's possible to provide some options like saving tabs as a list, but it won't be automatic since extensions can't write to files directly.

Hope that helps!
